### ISSUE TITLE
The requested module '/_snowpack/pkg/@walletconnect.environment.v1.0.0.js' does not provide an export named 'formatErrorMessage'

### ISSUE THREAD

**Issue by crapthings** [WalletConnect/walletconnect-utils#11]
Uncaught (in promise) SyntaxError: The requested module '/_snowpack/pkg/@walletconnect.environment.v1.0.0.js' does not provide an export named 'formatErrorMessage'

```
import WalletConnectProvider from '@walletconnect/web3-provider'
```

after i import provider

**Comment by crapthings** [comment]
node_modules/.cache/snowpack/build/%40walletconnect/jsonrpc-utils%401.0.0/%40walletconnect/jsonrpc-utils.js

it looks '@walletconnect/environment' doesn't have these exports

```js
export { formatErrorMessage, formatJsonRpcError, formatJsonRpcRequest, formatJsonRpcResult, isHttpUrl, isJsonRpcError, isJsonRpcPayload, isJsonRpcRequest, isJsonRpcResponse, isJsonRpcResult, isJsonRpcValidationInvalid, isLocalhostUrl, isValidDefaultRoute, isValidLeadingWildcardRoute, isValidRoute, isValidTrailingWildcardRoute, isValidWildcardRoute, isWsUrl, payloadId } from '@walletconnect/environment';
```

**Comment by pc-erin** [comment]
Is this a bug with snowpack? As far as I can tell, jsonrpc-utils isn't trying to import `formatErrorMessage` from `@walletconnect/environment`, it's exporting that function itself. Why has snowpack compiled it down to that?

**Comment by crapthings** [comment]
@pc-erin 

yes, I've changed bundler to parcel, it works.
