### ISSUE TITLE
SafeJSON.JSONParse mangles number inside of string literal

### ISSUE THREAD

**Issue by ian-eulith** [WalletConnect/walletconnect-utils#145]
We hit this bug while trying to use WalletConnect with [Dodo](https://app.dodoex.io/).

Test case:

```typescript
it("should handle number inside string literal", () => {
  const nested = '{"params":{"proposer":{"metadata":{"description":"Trade Any Token on DODOEX. Swap ETH to WETH at 0.99852536006139370845107244063040676283327993685155310925333096461126073315184832, 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE, 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"}}}}';
  const result = safeJsonParse(nested);
  chai.expect(result).to.deep.eq(JSON.parse(nested));
});
```

The problem is that safe-json [uses a regex to parse big numbers](https://github.com/WalletConnect/walletconnect-utils/blob/master/misc/safe-json/src/index.ts#L26), but this regex does not respect the structure of JSON objects.

It would also be good if the library didn't [swallow the error](https://github.com/WalletConnect/walletconnect-utils/blob/master/misc/safe-json/src/index.ts#L45) as this causes problems higher-up which are difficult to diagnose.

**Comment by arein** [comment]
Welcome to submit a pull request with an improvement - will flag this to the team
