### ISSUE TITLE
[BUG] "this.provider.disconnect" seems faulty

### ISSUE THREAD

**Issue by arujjval** [WalletConnect/walletconnect-utils#200]
I am using Rainbowkit + Nextjs (typescript). There is a problem that keeps occurring. After some hot-reloading of the page, an error keeps occurring 

`index.es.js:99 Uncaught (in promise) TypeError: this.provider.disconnect is not a function`

![Screenshot from 2024-10-11 07-25-32](https://github.com/user-attachments/assets/788ea843-7915-4ec8-851b-4169b659b3b2)

After reloading when this error occurs, the page shows that you are not connected to the internet (which there is no need for, I am developing locally).

I have tried reinstalling all modules. But it did not work.

Any idea what the reason is?

**Comment by bkrem** [comment]
Gm, this was patched in https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.17.2

Please let us know if you can still reproduce in latest Rainbowkit 🙏
