### ISSUE TITLE
`JsonRpcProvider` incompatibilities with `SignerConnection`

### ISSUE THREAD

**Issue by Harasz** [WalletConnect/walletconnect-utils#3]
Hi,
I found a `JsonRpcProvider` incompatibilities with `SignerConnection`. 
Basically the problem is that when we are using `SignerConnection` as a connection the method `open` is not called. That leads to the problem when event listeners for `payload`, `error` and `close` are not set. Because of that promise from `requestStrict` method can't be resolved. 
In my project I had to patch `JsonRpcProvider` by adding missing listeners.  Here are the changes: https://github.com/energywebfoundation/iam-client-lib/blob/3f114c32ca35c262e30cd4bc437a9c6d0a8c4dac/patches/%40walletconnect%2Bjsonrpc-provider%2B1.0.0.patch.

I am ready to prepare a fix for that, just let me know.

**Comment by pedrouid** [comment]
This is addressed on #7 right? I will be publishing it soon
