### ISSUE TITLE
How do you run the tests?

### ISSUE THREAD

**Issue by Luzzotica** [WalletConnect/walletconnect-utils#45]
npm run test gives me the following error:

```
lerna ERR! npm run test exited 127 in '@walletconnect/window-getters'
lerna ERR! npm run test stdout:

> @walletconnect/window-getters@1.0.1 test
> env TS_NODE_PROJECT="tsconfig.cjs.json" mocha --timeout 5000 --exit -r ts-node/register ./test/**/*.test.ts

lerna ERR! npm run test stderr:
env: mocha: No such file or directory
lerna ERR! npm run test exited 127 in '@walletconnect/window-getters'
```

I installed lerna globally, and inited it in the package, but it hasn't changed anything.

Could you update the readme with info on how to test this please?

**Comment by bkrem** [comment]
Thanks for raising. Readme has been updated since: https://github.com/WalletConnect/walletconnect-utils#setup
