### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by signorbusi** [WalletConnect/walletconnect-utils#47]
We get a lot of error reports in Sentry with the error `Uncaught TypeError: Cannot read properties of undefined (reading 'message')`. 

The offending line seems to be here: https://github.com/WalletConnect/walletconnect-utils/blob/22e46347e607b33f7579b30af6597c568eb7ccfb/jsonrpc/utils/src/error.ts#L66

Not super important but a small check if the message is defined would already help to get rid of the error reports.

Screenshot of the error stack in Chrome:

![image](https://user-images.githubusercontent.com/100610608/211824008-bcc441ca-21df-4bfe-ae0f-7d0b8a83b575.png)

**Comment by gergana95** [comment]
Same issue on my side. This happens on loocalhost on computer sleep/lock.

<img width="1440" alt="Screenshot 2023-01-13 at 10 09 25" src="https://user-images.githubusercontent.com/29689645/212280683-cfa1a615-3f63-4263-a49d-4d310424eb9d.png">

**Comment by bkrem** [comment]
Thank you for the original reports here, this should be fixed. 

Please report if still reproducible and we will reopen.
