### ISSUE TITLE
Check inputs in the parseConnectionError API

### ISSUE THREAD

**Issue by dfordivam** [WalletConnect/walletconnect-utils#8]
Hi

I have mentioned about the following problem of error handling of websocket here 
https://github.com/WalletConnect/walletconnect-monorepo/issues/548#issuecomment-1057572355

The fix to this is simply to add `(e != undefined)` check in the `parseConnectionError` API

```
WebSocket connection to 'wss://relay.walletconnect.org/?env=browser&host=localhost%3A8001&projectId=...&protocol=wc&version=2' failed: Error during WebSocket handshake: Unexpected response code: 502
 Uncaught TypeError: Cannot read property 'message' of undefined
```

**Comment by VuManh-07** [comment]
how to add (e != undefined) ? I still can't configure

**Comment by VuManh-07** [comment]
![image](https://user-images.githubusercontent.com/91170967/190394584-c23d4eea-da33-4e12-92ca-115f071fa288.png)
